### PR TITLE
Create Beautiful and Resposive Log In Page

### PR DESCRIPTION
**Pull request by ShikhaKumari01**

### CODE REVIEW

**Comment by surajsharma14** [comment]
@ShikhaKumari01 follow me so that i will merge it..

**Comment by surajsharma14** [comment]
@ShikhaKumari01 last few hours remains do it asap and msg me that you done it.

**Comment by ShikhaKumari01** [comment]
This repo has been excluded from the event. But the second pull request(calculator) that you merged is not. I have complete 3 pull requests but was unable to complete the 4th one. Now, that 4th one is also done because of you.
Thank you!

**Comment by ShikhaKumari01** [comment]
Screenshot (162)
Screenshot (163)

**Pull request merged**
