### PR TITLE
Create game_snake.py

### PR DESCRIPTION
**Pull request by KHUSHIKUMARI123**

### CODE REVIEW

**Comment by surajsharma14** [comment]
@KHUSHIKUMARI123 Make sure follow me so that your Pull requested counted as a valid contribution.

**Comment by surajsharma14** [comment]
do that and let us know so that i can review and merge it.

**Comment by KHUSHIKUMARI123** [comment]
If I follow u then u will accept all my repo pull request too. Because
already I'm going to follow you.

**Comment by KHUSHIKUMARI123** [comment]
Sir u can see I'm following you and  now u should accept all pull request
and make it valid..

**Comment by surajsharma14** [comment]
okk fine

**Comment by KHUSHIKUMARI123** [comment]
Hello Sir.

My repo was not accepted by you. So pls accept my request and add the label
of Hacktoberfest 2023 or Hacktoberfest accepted. So that it can get count
for my Hacktoberfest event.

Thank you.

**Pull request merged**
