### PR TITLE
First Commit from KaushalSonic

### PR DESCRIPTION
**Pull request by KaushalSonic**
Uploaded BIRTHDAY card.

### CODE REVIEW

**Comment by surajsharma14** [comment]
@KaushalSonic  alright thats interesting . i am going to merge it but before that make sure you follow me so that your PR counted in valid contribution. and connect with me in other social handle for such amazing opportunities.

**Comment by KaushalSonic** [comment]
Hey @surajsharma14 , I forgot to add "hacktoberfest-accepted" label on the pull request. So, it didn't got count. :(

**Comment by KaushalSonic** [comment]
So allow me to change in this file and then with the branch let me PR to you.

**Comment by KaushalSonic** [comment]
I tried but that method, it doesn't work, I have to PR again with a new repo, So I will re-upload them, But CAN you delete "Birthday-card.html" & "Birthday-card.css" , It will get redundant.

**Pull request merged**
