### PR TITLE
Create aditi1

### PR DESCRIPTION
**Pull request by Aditiwari05**

### CODE REVIEW

**Comment by surajsharma14** [comment]
@Aditiwari05 I recieved your Pull Request make sure you follow me so that i can merge. and your PR will be going to count valid.

**Comment by Aditiwari05** [comment]
Okay

**Comment by surajsharma14** [comment]
okk done

**Comment by surajsharma14** [comment]
@Aditiwari05 congratulation your initial contrubution done....

**Comment by Aditiwari05** [comment]
Thanks a lot.

**Comment by Aditiwari05** [comment]
Can you please tell me why it's showing this?
Actually this is the very first time I'm attending hacktoberfest and i
don't have that much knowledge about it.

**Comment by surajsharma14** [comment]
means what showing...i am not able to understand. its from own side merged. what is showing from your end. just send me snapshot .

**Comment by Aditiwari05** [comment]
I've already sent you in the mail!

**Pull request merged**
