### PR TITLE
Weather-App

### PR DESCRIPTION
**Pull request by shivang21007**
**This is Weather-forcast Web-App.**
- Resolve - #66
- Made using HTML, CSS, Javacsript
- A beautiful **UI using Bootstrap**.
 - **Real-time** Weather data from **Open-Weather API** 

image

- In future I will add more features and Ineractive UI.
- if you have any issue , kindly tell me :)

### CODE REVIEW

**Comment by surajsharma14** [comment]
@shivang21007 okay cool... follow me so that i can merge and that PR will count in valid contribution.

**Comment by surajsharma14** [comment]
when you done just ping me i will merge it, okk

**Comment by shivang21007** [comment]
@surajsharma14 
- I followed you
- and merge it for now, I will add more feature in another PR .

**Comment by surajsharma14** [comment]
done

**Comment by surajsharma14** [comment]
@shivang21007 congratulations

**Comment by shivang21007** [comment]
@surajsharma14 
- can you please mark this issue under hackoctoberfest , like this -
image

**Comment by shivang21007** [comment]
@surajsharma14 
- ## this PR is not valid PR under hacktoberfest,
image


- ## You need to assign these label with PR, so that hacktober can know my PRs.
image



- ## from next time first add these label and then merge it also, you have to mention on these labels on each issue.

**Pull request merged**
